name: Build and Deploy to EKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 061039777231.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build Docker Image
      run: |
        docker build -t gym-app .
        docker tag gym-app:latest 061039777231.dkr.ecr.ap-south-1.amazonaws.com/gym-app:latest

    - name: Push to ECR
      run: |
        docker push 061039777231.dkr.ecr.ap-south-1.amazonaws.com/gym-app:latest

    - name: Set up kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name gym-app-cluster

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s-manifests/
